import React from 'react';
import { AlertTriangle, Calendar, Flame, PlusCircle, Sparkles } from 'lucide-react';
import { CookLog, SmokerProfile } from '../types';

type Props = { profile: SmokerProfile; cookLogs: CookLog[]; tempUnit: 'F'|'C'; onOpenCharGPT:(prompt?:string)=>void; onOpenPlanner:()=>void; onOpenNewCook:()=>void };

export const HomeCommandCenter: React.FC<Props> = ({ profile, cookLogs, tempUnit, onOpenCharGPT, onOpenPlanner, onOpenNewCook }) => {
  const cook = cookLogs.find(c => c.status === 'In Progress') || null;
  const reading = cook?.temperatureReadings?.length ? cook.temperatureReadings[cook.temperatureReadings.length - 1] : null;
  const fact = (v: unknown, suffix='') => typeof v === 'number' && Number.isFinite(v) ? `${v}${suffix}` : 'Not recorded';
  const prompt = (rescue=false) => cook ? `${rescue ? 'Rescue Mode. Diagnose what may be wrong.' : 'What should I do next?'} Use only recorded facts and verified knowledge. Do not invent missing readings or equipment specifications.\nCook: ${cook.title || cook.proteinCut || 'active cook'}\nProtein: ${cook.proteinCut || cook.proteinType || 'not recorded'}\nPit temperature: ${fact(reading?.cookingTemp, `°${tempUnit}`)}\nMeat temperature: ${fact(reading?.meatTemp, `°${tempUnit}`)}\nTarget temperature: ${fact(reading?.targetTemp, `°${tempUnit}`)}\nLogged duration: ${fact(cook.hoursLogged, ' hours')}\nLast action: ${reading?.actionsTaken || 'not recorded'}` : `Help me plan what to do next with ${profile.name || profile.model || 'my smoker'}. Use verified equipment knowledge where available and ask for missing facts.`;

  if (!cook) return <section className="mb-6 rounded-2xl border border-zinc-800 bg-[#181818] p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-extrabold text-white"><Sparkles className="mr-2 inline h-5 w-5 text-purple-400"/>CharGPT Command Center</h2><p className="mt-1 text-xs text-zinc-400">No in-progress cook is recorded.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>onOpenCharGPT(prompt())} className="rounded-xl bg-purple-600 px-4 py-2 text-xs font-bold text-white">ASK CHARGPT</button><button onClick={onOpenPlanner} className="rounded-xl border border-zinc-700 px-4 py-2 text-xs font-bold text-zinc-200"><Calendar className="mr-1 inline h-4 w-4"/>PLAN COOK</button><button onClick={onOpenNewCook} className="rounded-xl bg-orange-500 px-4 py-2 text-xs font-extrabold text-zinc-950"><PlusCircle className="mr-1 inline h-4 w-4"/>START NEW COOK</button></div></div></section>;

  return <section className="mb-6 rounded-2xl border-2 border-orange-500/40 bg-[#181818] p-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-orange-500 p-3 text-zinc-950"><Flame className="h-5 w-5"/></div><div><div className="text-[10px] font-bold uppercase text-orange-400">Active cook in progress</div><h2 className="text-lg font-extrabold text-white">{cook.title || cook.proteinCut}</h2></div></div><div className="my-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Pit Temp" value={fact(reading?.cookingTemp, `°${tempUnit}`)}/><Metric label="Meat Probe" value={fact(reading?.meatTemp, `°${tempUnit}`)}/><Metric label="Target Temp" value={fact(reading?.targetTemp, `°${tempUnit}`)}/><Metric label="Duration" value={fact(cook.hoursLogged, ' hrs')}/></div><div className="flex flex-wrap gap-2"><button onClick={()=>onOpenCharGPT(prompt())} className="rounded-xl bg-orange-500 px-4 py-2 text-xs font-extrabold text-zinc-950">WHAT'S NEXT?</button><button onClick={()=>onOpenCharGPT(prompt(true))} className="rounded-xl border border-red-500/30 bg-red-500/15 px-4 py-2 text-xs font-extrabold text-red-300"><AlertTriangle className="mr-1 inline h-4 w-4"/>RESCUE MODE</button></div></section>;
};

const Metric: React.FC<{label:string;value:string}> = ({label,value}) => <div className="rounded-xl border border-zinc-800 bg-zinc-900/80 p-3 text-center"><div className="text-[10px] font-bold uppercase text-zinc-500">{label}</div><div className="mt-1 font-mono text-sm font-extrabold text-zinc-100">{value}</div></div>;
