import { ProteinType, FuelBlendComponent } from '../types';
import { calculateBlendPhysics, BlendPhysicsResult } from './fuelBlendPhysics';

export interface FuelDatabaseItem {
  id: string;
  name: string;
  brand: string;
  category: 'Pure Wood Species' | 'Commercial Pellets' | 'Pitmaster Blends' | 'Charcoal & Lump' | 'Smoker Wood Chips';
  btuPerLb: number;
  moisturePercent: number;
  smokeDensity: 'Light' | 'Medium' | 'Bold' | 'Heavy';
  barkImpact: string;
  flavorNotes: string;
  recommendedProteins: ProteinType[];
  blendRatioSummary?: string;
  blendComponents?: FuelBlendComponent[];
  ashOutput: 'Ultra Low (<0.5%)' | 'Low (0.5-0.8%)' | 'Standard (1.0%)' | 'Moderate';
  idealSmokingTempRange: string;
  tags: string[];
  description: string;
  burnRateEfficiencyRating: number; // e.g. 92%
  estimatedRunTimeHoursPer10Lbs: number; // e.g. 8.8 hrs
}

export const FUEL_AND_WOOD_DATABASE: FuelDatabaseItem[] = [
  // --- PURE WOOD SPECIES ---
  {
    id: 'spec-post-oak',
    name: 'Post Oak',
    brand: 'Pure Wood Species',
    category: 'Pure Wood Species',
    btuPerLb: 8600,
    moisturePercent: 6.0,
    smokeDensity: 'Medium',
    barkImpact: 'Deep Mahogany & Firm Bark',
    flavorNotes: 'Clean, balanced, classic Central Texas smoke flavor that lets the natural beef or pork taste shine.',
    recommendedProteins: ['Beef', 'Pork', 'Lamb', 'Bison'],
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 275°F',
    tags: ['Texas', 'Brisket', 'Classic', 'Central Texas', 'Mahogany Bark'],
    description: 'The undisputed king of Texas barbecue wood. Burns clean with steady thermal output and builds rich mahogany bark without overpowering meat.',
    burnRateEfficiencyRating: 91.5,
    estimatedRunTimeHoursPer10Lbs: 8.8,
  },
  {
    id: 'spec-hickory',
    name: 'Hickory',
    brand: 'Pure Wood Species',
    category: 'Pure Wood Species',
    btuPerLb: 8800,
    moisturePercent: 6.5,
    smokeDensity: 'Bold',
    barkImpact: 'Dark Espresso & Heavy Bark',
    flavorNotes: 'Rich, pungent, bacon-like savory aroma. Classic Southern BBQ staple that creates a distinct smoke ring.',
    recommendedProteins: ['Pork', 'Chicken', 'Turkey', 'Wild Boar', 'Venison'],
    ashOutput: 'Standard (1.0%)',
    idealSmokingTempRange: '225°F - 250°F',
    tags: ['Bacon', 'Southern', 'Ribs', 'Pulled Pork', 'Bold Smoke'],
    description: 'The foundation of traditional Southern barbecue. Delivers strong, pungent, savory smoke notes perfect for long pork shoulder and rib cooks.',
    burnRateEfficiencyRating: 92.0,
    estimatedRunTimeHoursPer10Lbs: 9.0,
  },
  {
    id: 'spec-pecan',
    name: 'Pecan',
    brand: 'Pure Wood Species',
    category: 'Pure Wood Species',
    btuPerLb: 8700,
    moisturePercent: 6.2,
    smokeDensity: 'Medium',
    barkImpact: 'Golden Mahogany',
    flavorNotes: 'Smooth, sweet, subtle nuttiness without harshness. Excellent versatile all-rounder wood.',
    recommendedProteins: ['Pork', 'Beef', 'Chicken', 'Turkey', 'Lamb'],
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 275°F',
    tags: ['Nutty', 'Versatile', 'Smooth', 'All-Rounder', 'Sweet'],
    description: 'A member of the hickory family, but burns smoother and sweeter with a subtle nutty aroma that never turns bitter.',
    burnRateEfficiencyRating: 91.8,
    estimatedRunTimeHoursPer10Lbs: 8.9,
  },
  {
    id: 'spec-cherry',
    name: 'Cherry',
    brand: 'Pure Wood Species',
    category: 'Pure Wood Species',
    btuPerLb: 8200,
    moisturePercent: 7.0,
    smokeDensity: 'Light',
    barkImpact: 'Vibrant Deep Red Mahogany',
    flavorNotes: 'Sweet, fruity, subtle smoke that gives meat an incredible reddish hue and golden skin.',
    recommendedProteins: ['Pork', 'Chicken', 'Duck', 'Turkey', 'Seafood'],
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 300°F',
    tags: ['Fruity', 'Red Bark', 'Poultry', 'Ribs', 'Sweet'],
    description: 'Prized by competition pitmasters for imparting a gorgeous dark red hue to pork ribs, turkey, and chicken skins.',
    burnRateEfficiencyRating: 88.5,
    estimatedRunTimeHoursPer10Lbs: 8.2,
  },
  {
    id: 'spec-apple',
    name: 'Apple',
    brand: 'Pure Wood Species',
    category: 'Pure Wood Species',
    btuPerLb: 8100,
    moisturePercent: 7.2,
    smokeDensity: 'Light',
    barkImpact: 'Warm Light Amber',
    flavorNotes: 'Mildly sweet and mellow fruity notes. Takes time to build heavy smoke without overpowering delicate meat.',
    recommendedProteins: ['Pork', 'Chicken', 'Turkey', 'Seafood'],
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 275°F',
    tags: ['Fruitwood', 'Mellow', 'Sweet', 'Pork Loin', 'Mild'],
    description: 'A delicate fruitwood that imparts a subtle, sweet, crisp apple flavor. Ideal for pork chops, bacon, and poultry.',
    burnRateEfficiencyRating: 87.8,
    estimatedRunTimeHoursPer10Lbs: 8.0,
  },
  {
    id: 'spec-mesquite',
    name: 'Mesquite',
    brand: 'Pure Wood Species',
    category: 'Pure Wood Species',
    btuPerLb: 9200,
    moisturePercent: 5.5,
    smokeDensity: 'Heavy',
    barkImpact: 'Dark Black & Intense Sear',
    flavorNotes: 'Extremely hot burn, sharp earthy aroma. Best for fast high-heat sears or heavy cuts like brisket flat.',
    recommendedProteins: ['Beef', 'Bison', 'Wild Game', 'Elk'],
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '250°F - 350°F',
    tags: ['High Heat', 'Intense', 'Texas Desert', 'Sear', 'Bold'],
    description: 'The highest BTU wood species in North America. Produces intense, rapid heat and robust, sharp earthen smoke.',
    burnRateEfficiencyRating: 95.0,
    estimatedRunTimeHoursPer10Lbs: 9.6,
  },
  {
    id: 'spec-maple',
    name: 'Sugar Maple',
    brand: 'Pure Wood Species',
    category: 'Pure Wood Species',
    btuPerLb: 8400,
    moisturePercent: 6.8,
    smokeDensity: 'Medium',
    barkImpact: 'Light Tan & Smooth Glaze',
    flavorNotes: 'Sweet, gentle wood smoke with delicate syrup undertones that complement glazes and sweet rubs.',
    recommendedProteins: ['Pork', 'Chicken', 'Turkey', 'Pheasant'],
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 275°F',
    tags: ['Syrup', 'Sweet', 'Ham', 'Poultry', 'Glaze'],
    description: 'Mild and sweet with a distinct light syrup undertone. Perfect when smoking hams, pork chops, and roast turkey.',
    burnRateEfficiencyRating: 89.2,
    estimatedRunTimeHoursPer10Lbs: 8.4,
  },
  {
    id: 'spec-alder',
    name: 'Alder',
    brand: 'Pure Wood Species',
    category: 'Pure Wood Species',
    btuPerLb: 8000,
    moisturePercent: 7.5,
    smokeDensity: 'Light',
    barkImpact: 'Subtle Bronze Finish',
    flavorNotes: 'Delicate, neutral sweetness with light smoke density. Traditional Pacific Northwest seafood choice.',
    recommendedProteins: ['Seafood', 'Chicken', 'Turkey', 'Pheasant'],
    ashOutput: 'Ultra Low (<0.5%)',
    idealSmokingTempRange: '180°F - 250°F',
    tags: ['Salmon', 'Pacific NW', 'Fish', 'Delicate', 'Clean'],
    description: 'Light and neutral with delicate sweetness. Does not mask fish, salmon, or sea bass flavors.',
    burnRateEfficiencyRating: 86.5,
    estimatedRunTimeHoursPer10Lbs: 7.8,
  },
  {
    id: 'spec-peach',
    name: 'Peach',
    brand: 'Pure Wood Species',
    category: 'Pure Wood Species',
    btuPerLb: 8250,
    moisturePercent: 6.9,
    smokeDensity: 'Light',
    barkImpact: 'Golden Rose Mahogany',
    flavorNotes: 'Delicate fruity sweetness similar to hickory but milder and sweeter, producing a fragrant peach orchard aroma.',
    recommendedProteins: ['Pork', 'Chicken', 'Turkey', 'Duck'],
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 275°F',
    tags: ['Southern Fruit', 'Sweet', 'Ribs', 'Poultry'],
    description: 'A prized Southern fruitwood that produces a soft, aromatic sweet smoke with a rose-golden bark color.',
    burnRateEfficiencyRating: 88.8,
    estimatedRunTimeHoursPer10Lbs: 8.3,
  },
  {
    id: 'spec-almond',
    name: 'Almond Wood',
    brand: 'Pure Wood Species',
    category: 'Pure Wood Species',
    btuPerLb: 8950,
    moisturePercent: 5.8,
    smokeDensity: 'Medium',
    barkImpact: 'Deep Golden Chestnut',
    flavorNotes: 'Nutty, sweet, long-burning heat with smooth smoke profile. Similar to pecan with even higher thermal output.',
    recommendedProteins: ['Beef', 'Pork', 'Chicken', 'Lamb'],
    ashOutput: 'Ultra Low (<0.5%)',
    idealSmokingTempRange: '225°F - 300°F',
    tags: ['Almond', 'High BTU', 'California', 'Long Burn', 'Nutty'],
    description: 'Denser than oak with high heat output and very low ash. Delivers a clean nutty smoke profile suitable for long overnight cooks.',
    burnRateEfficiencyRating: 93.8,
    estimatedRunTimeHoursPer10Lbs: 9.3,
  },

  // --- COMMERCIAL BRAND PELLETS ---
  {
    id: 'brand-bear-mountain-comp',
    name: 'Bear Mountain BBQ - Competition Craft Blend',
    brand: 'Bear Mountain BBQ',
    category: 'Commercial Pellets',
    btuPerLb: 8750,
    moisturePercent: 5.8,
    smokeDensity: 'Medium',
    barkImpact: 'Deep Mahogany & Firm Bark',
    flavorNotes: 'Master blend of Oak, Hickory, and Cherry. Delivers a sweet, bold, perfectly balanced smoke for any meat.',
    recommendedProteins: ['Beef', 'Pork', 'Chicken', 'Turkey', 'Lamb'],
    blendRatioSummary: '40% Oak / 40% Hickory / 20% Cherry',
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 300°F',
    tags: ['100% Hardwood', 'Competition Blend', 'No Fillers', 'Low Ash', 'Best Seller'],
    description: '100% natural hardwood pellets with no oil additives or binder fillers. Offers robust flavor and steady burn temperature.',
    burnRateEfficiencyRating: 92.5,
    estimatedRunTimeHoursPer10Lbs: 9.1,
  },
  {
    id: 'brand-lumberjack-comp',
    name: 'Lumberjack - Competition Blend',
    brand: 'Lumberjack Pellets',
    category: 'Commercial Pellets',
    btuPerLb: 8820,
    moisturePercent: 5.5,
    smokeDensity: 'Bold',
    barkImpact: 'Rich Espresso Mahogany',
    flavorNotes: '34% Maple, 33% Hickory, 33% Cherry processed with bark on for maximum smoke ring penetration.',
    recommendedProteins: ['Beef', 'Pork', 'Chicken', 'Turkey', 'Wild Boar'],
    blendRatioSummary: '34% Maple / 33% Hickory / 33% Cherry',
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 275°F',
    tags: ['Whole Tree', 'Bark Included', 'Heavy Smoke Ring', 'Pro Favorite'],
    description: 'Renowned among pitmasters for using whole-tree logs including natural bark to maximize authentic smoke flavor and ring creation.',
    burnRateEfficiencyRating: 93.0,
    estimatedRunTimeHoursPer10Lbs: 9.2,
  },
  {
    id: 'brand-jealous-devil-jax',
    name: 'Jealous Devil - Jax Legend Hardwood Blend',
    brand: 'Jealous Devil',
    category: 'Commercial Pellets',
    btuPerLb: 8900,
    moisturePercent: 5.2,
    smokeDensity: 'Bold',
    barkImpact: 'Deep Dark Chocolate Bark',
    flavorNotes: 'Virgin virgin hardwood blend of Hickory, Oak, and Cherry. Extremely dense pellet structure with clean burn.',
    recommendedProteins: ['Beef', 'Pork', 'Bison', 'Wild Game'],
    blendRatioSummary: 'Oak / Hickory / Cherry Virgin Wood',
    ashOutput: 'Ultra Low (<0.5%)',
    idealSmokingTempRange: '225°F - 325°F',
    tags: ['Virgin Wood', 'Ultra Low Ash', 'Heavy Weight', 'High BTU'],
    description: 'Crafted from 100% virgin American hardwoods. Ultra-dense pellets burn hotter and longer with under 0.5% ash residue.',
    burnRateEfficiencyRating: 94.2,
    estimatedRunTimeHoursPer10Lbs: 9.4,
  },
  {
    id: 'brand-cookinpellets-perfect-mix',
    name: 'CookinPellets - The Perfect Mix',
    brand: 'CookinPellets',
    category: 'Commercial Pellets',
    btuPerLb: 8780,
    moisturePercent: 5.6,
    smokeDensity: 'Medium',
    barkImpact: 'Rich Red Mahogany',
    flavorNotes: '4 base hardwoods: Hickory, Cherry, Hard Maple, and Apple. 100% pure base species with zero alder or oak filler.',
    recommendedProteins: ['Pork', 'Chicken', 'Beef', 'Turkey'],
    blendRatioSummary: '25% Hickory / 25% Cherry / 25% Maple / 25% Apple',
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 275°F',
    tags: ['No Alder Filler', '4-Wood Mix', 'Competition Grade', 'Sweet Smoke'],
    description: 'Uses 100% of the named hardwoods without using cheap alder or oak base fillers, delivering authentic fruit and hickory smoke.',
    burnRateEfficiencyRating: 92.4,
    estimatedRunTimeHoursPer10Lbs: 9.0,
  },
  {
    id: 'brand-knottywood-almond',
    name: 'Knotty Wood - 100% Pure Almond Wood Pellets',
    brand: 'Knotty Wood',
    category: 'Commercial Pellets',
    btuPerLb: 8980,
    moisturePercent: 5.0,
    smokeDensity: 'Medium',
    barkImpact: 'Deep Golden Bark',
    flavorNotes: '100% pure California Almond wood. Sweet, subtle nuttiness with high heat output and beautiful golden bark.',
    recommendedProteins: ['Beef', 'Pork', 'Chicken', 'Lamb', 'Seafood'],
    blendRatioSummary: '100% Pure Almond Wood',
    ashOutput: 'Ultra Low (<0.5%)',
    idealSmokingTempRange: '225°F - 350°F',
    tags: ['100% Almond', 'California Orchard', 'High Heat', 'Unique Flavor'],
    description: 'Single-origin almond wood harvested from California orchards. High density provides exceptional burn times and sweet nutty smoke.',
    burnRateEfficiencyRating: 94.8,
    estimatedRunTimeHoursPer10Lbs: 9.5,
  },
  {
    id: 'brand-bb-championship',
    name: 'B&B Charcoal - Championship Blend Pellets',
    brand: 'B&B Charcoal',
    category: 'Commercial Pellets',
    btuPerLb: 8850,
    moisturePercent: 5.4,
    smokeDensity: 'Bold',
    barkImpact: 'Classic Texas Dark Bark',
    flavorNotes: 'Post Oak, Pecan, and Cherry hardwood blend created specifically for Texas competition brisket and rib cooks.',
    recommendedProteins: ['Beef', 'Pork', 'Turkey'],
    blendRatioSummary: 'Post Oak / Pecan / Cherry',
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 275°F',
    tags: ['Texas Barbecue', 'Championship', 'Post Oak Base', 'Brisket Choice'],
    description: 'Formulated by championship pitmasters in Texas. Post Oak backbone provides authentic smoke while Pecan and Cherry add sweet aroma.',
    burnRateEfficiencyRating: 93.2,
    estimatedRunTimeHoursPer10Lbs: 9.2,
  },
  {
    id: 'brand-royal-oak-charcoal-pellets',
    name: 'Royal Oak - 100% Charcoal Hardwood Pellets',
    brand: 'Royal Oak',
    category: 'Charcoal & Lump',
    btuPerLb: 9650,
    moisturePercent: 4.2,
    smokeDensity: 'Bold',
    barkImpact: 'Pitch Black Sear & Crust',
    flavorNotes: '100% real hardwood lump charcoal condensed into pellet form. Delivers authentic charcoal grill flavor and high searing heat.',
    recommendedProteins: ['Beef', 'Pork', 'Bison', 'Wild Game'],
    blendRatioSummary: '100% Hardwood Lump Charcoal',
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '250°F - 450°F',
    tags: ['Charcoal Pellets', 'High Heat Sear', 'Steak', 'Lump Flavor', '9000+ BTU'],
    description: 'Combines the precise digital temperature control of a pellet smoker with the high heat and authentic aroma of lump charcoal.',
    burnRateEfficiencyRating: 96.0,
    estimatedRunTimeHoursPer10Lbs: 9.8,
  },
  {
    id: 'brand-jealous-devil-charcoal-pellets',
    name: 'Jealous Devil - Jax Charcoal Hardwood Pellets',
    brand: 'Jealous Devil',
    category: 'Charcoal & Lump',
    btuPerLb: 9750,
    moisturePercent: 4.0,
    smokeDensity: 'Bold',
    barkImpact: 'Jet Black Intense Crust',
    flavorNotes: 'Ultra-dense South American hardwood charcoal pellets. Extreme BTU thermal yield and near-zero ash residue.',
    recommendedProteins: ['Beef', 'Bison', 'Wild Game', 'Other'],
    blendRatioSummary: '100% South American Charcoal Hardwood',
    ashOutput: 'Ultra Low (<0.5%)',
    idealSmokingTempRange: '250°F - 500°F',
    tags: ['Charcoal Pellets', 'Jealous Devil', 'High Heat', 'Ultra Low Ash'],
    description: 'Premier charcoal pellets engineered for searing steaks and maintaining long, steady thermal stability with minimal ash.',
    burnRateEfficiencyRating: 97.2,
    estimatedRunTimeHoursPer10Lbs: 10.1,
  },
  {
    id: 'brand-pitboss-charcoal-pellets',
    name: 'Pit Boss - Charcoal Hardwood Pellets',
    brand: 'Pit Boss',
    category: 'Charcoal & Lump',
    btuPerLb: 9500,
    moisturePercent: 4.9,
    smokeDensity: 'Medium',
    barkImpact: 'Dark Charred Mahogany',
    flavorNotes: 'Natural oak hardwood charcoal blend. Adds traditional backyard charcoal grill taste to any pellet cooker.',
    recommendedProteins: ['Beef', 'Pork', 'Chicken', 'Other'],
    blendRatioSummary: 'Oak Charcoal Hardwood Blend',
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 450°F',
    tags: ['Pit Boss', 'Charcoal Pellets', 'Versatile', 'High BTU'],
    description: 'All-natural charcoal hardwood pellets combining low-and-slow smoking capabilities with high-temperature roasting.',
    burnRateEfficiencyRating: 95.0,
    estimatedRunTimeHoursPer10Lbs: 9.6,
  },
  {
    id: 'brand-traeger-signature',
    name: 'Traeger - Signature Blend Hardwood Pellets',
    brand: 'Traeger',
    category: 'Commercial Pellets',
    btuPerLb: 8550,
    moisturePercent: 6.5,
    smokeDensity: 'Medium',
    barkImpact: 'Classic Mahogany Bark',
    flavorNotes: 'Signature combination of Hickory, Maple, and Cherry. Balanced everyday smoke profile for all meats.',
    recommendedProteins: ['Beef', 'Pork', 'Chicken', 'Turkey'],
    blendRatioSummary: 'Hickory / Maple / Cherry',
    ashOutput: 'Standard (1.0%)',
    idealSmokingTempRange: '225°F - 300°F',
    tags: ['Traeger', 'Signature', 'Hickory', 'Cherry', 'Everyday Blend'],
    description: 'Traeger\'s flagship all-around blend delivering versatile savory-sweet hardwood smoke.',
    burnRateEfficiencyRating: 90.8,
    estimatedRunTimeHoursPer10Lbs: 8.7,
  },
  {
    id: 'brand-traeger-texas-beef',
    name: 'Traeger - Texas Beef Blend Pellets',
    brand: 'Traeger',
    category: 'Commercial Pellets',
    btuPerLb: 8850,
    moisturePercent: 5.8,
    smokeDensity: 'Bold',
    barkImpact: 'Deep Texas Dark Bark',
    flavorNotes: 'Oak, Mesquite, and Pecan blend created for heavy beef cuts, brisket, and beef ribs.',
    recommendedProteins: ['Beef', 'Bison', 'Lamb'],
    blendRatioSummary: 'Oak / Mesquite / Pecan',
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 275°F',
    tags: ['Traeger', 'Texas Beef', 'Brisket', 'Mesquite', 'Oak'],
    description: 'Bold Texas-style blend crafted to penetrate thick beef cuts with rich savory smoke.',
    burnRateEfficiencyRating: 93.0,
    estimatedRunTimeHoursPer10Lbs: 9.2,
  },
  {
    id: 'brand-pitboss-competition',
    name: 'Pit Boss - Competition Blend Pellets',
    brand: 'Pit Boss',
    category: 'Commercial Pellets',
    btuPerLb: 8620,
    moisturePercent: 6.3,
    smokeDensity: 'Medium',
    barkImpact: 'Warm Mahogany Finish',
    flavorNotes: 'Versatile blend of Maple, Hickory, and Apple hardwood pellets with smooth, mild sweetness.',
    recommendedProteins: ['Beef', 'Pork', 'Chicken', 'Turkey'],
    blendRatioSummary: 'Maple / Hickory / Apple',
    ashOutput: 'Standard (1.0%)',
    idealSmokingTempRange: '225°F - 300°F',
    tags: ['Pit Boss', 'Competition', 'Maple', 'Apple', 'Sweet'],
    description: 'Smooth combination of hardwoods suitable for ribs, chicken, pork butts, and flame-broiling.',
    burnRateEfficiencyRating: 91.5,
    estimatedRunTimeHoursPer10Lbs: 8.9,
  },
  {
    id: 'brand-jack-daniels-whiskey',
    name: 'Jack Daniel\'s - Whiskey Barrel Wood Pellets',
    brand: 'Jack Daniel\'s',
    category: 'Commercial Pellets',
    btuPerLb: 8950,
    moisturePercent: 5.6,
    smokeDensity: 'Bold',
    barkImpact: 'Rich Charcoal Mahogany Bark',
    flavorNotes: 'Crafted from authentic white oak Jack Daniel\'s Tennessee whiskey aging barrels with sweet whiskey mash aroma.',
    recommendedProteins: ['Beef', 'Pork', 'Venison', 'Wild Game'],
    blendRatioSummary: '100% Jack Daniel\'s Oak Barrel',
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 325°F',
    tags: ['Whiskey Barrel', 'Jack Daniel\'s', 'Oak', 'Premium', 'Aroma'],
    description: 'Infuses meats with the legendary sweet oak mash aroma of authentic Tennessee whiskey barrels.',
    burnRateEfficiencyRating: 94.0,
    estimatedRunTimeHoursPer10Lbs: 9.4,
  },
  {
    id: 'brand-knottywood-plum',
    name: 'Knotty Wood - 100% Pure Plum Wood Pellets',
    brand: 'Knotty Wood',
    category: 'Commercial Pellets',
    btuPerLb: 8520,
    moisturePercent: 6.2,
    smokeDensity: 'Medium',
    barkImpact: 'Crimson Mahogany Red Bark',
    flavorNotes: '100% pure plum fruit wood. Sweet, subtle fruit profile that imparts incredible ruby-red bark color.',
    recommendedProteins: ['Pork', 'Chicken', 'Seafood'],
    blendRatioSummary: '100% Pure Plum Wood',
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 275°F',
    tags: ['100% Plum', 'Fruitwood', 'Red Bark', 'Knotty Wood'],
    description: 'Unique fruitwood pellets sourced from California plum orchards, prized for rich red color on pork and poultry.',
    burnRateEfficiencyRating: 90.5,
    estimatedRunTimeHoursPer10Lbs: 8.6,
  },
  {
    id: 'brand-camp-chef-competition',
    name: 'Camp Chef - Competition Blend Pellets',
    brand: 'Camp Chef',
    category: 'Commercial Pellets',
    btuPerLb: 8580,
    moisturePercent: 6.4,
    smokeDensity: 'Medium',
    barkImpact: 'Golden Mahogany',
    flavorNotes: 'Maple, Hickory, and Cherry blend for sweet, smooth competition barbecue.',
    recommendedProteins: ['Pork', 'Chicken', 'Turkey'],
    blendRatioSummary: 'Maple / Hickory / Cherry',
    ashOutput: 'Standard (1.0%)',
    idealSmokingTempRange: '225°F - 275°F',
    tags: ['Camp Chef', 'Competition', 'Clean Burn'],
    description: 'High-grade hardwood pellets formulated for clean combustion and balanced smoke.',
    burnRateEfficiencyRating: 91.0,
    estimatedRunTimeHoursPer10Lbs: 8.8,
  },

  // --- PITMASTER MASTER CUSTOM BLENDS ---
  {
    id: 'blend-texas-brisket-master',
    name: 'Texas Hill Country Brisket Blend',
    brand: 'Pitmaster Master Blend',
    category: 'Pitmaster Blends',
    btuPerLb: 8640,
    moisturePercent: 6.1,
    smokeDensity: 'Medium',
    barkImpact: 'Firm Central Texas Dark Mahogany',
    flavorNotes: '60% Central Texas Post Oak with 40% Pecan for a balanced savory-nutty smoke that develops a firm mahogany bark over 14 hours.',
    recommendedProteins: ['Beef', 'Bison', 'Pork'],
    blendRatioSummary: '60% Post Oak / 40% Pecan',
    blendComponents: [
      { id: 'c1', woodType: 'Post Oak', percentage: 60 },
      { id: 'c2', woodType: 'Pecan', percentage: 40 },
    ],
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 250°F',
    tags: ['Brisket Special', 'Central Texas', 'Post Oak', 'Nutty', '12+ Hour Cook'],
    description: 'The standard blend used for award-winning beef brisket flats and points. Post Oak creates the bark structure while Pecan smoothes out the finish.',
    burnRateEfficiencyRating: 91.8,
    estimatedRunTimeHoursPer10Lbs: 8.9,
  },
  {
    id: 'blend-carolina-pig-roast',
    name: 'Carolina Whole Hog & Pork Shoulder Blend',
    brand: 'Pitmaster Master Blend',
    category: 'Pitmaster Blends',
    btuPerLb: 8660,
    moisturePercent: 6.4,
    smokeDensity: 'Bold',
    barkImpact: 'Dark Espresso with Cherry Rose Glaze',
    flavorNotes: '50% Hickory for heavy savory bacon aroma, 30% Apple for sweetness, and 20% Cherry for rich ruby red skin color.',
    recommendedProteins: ['Pork', 'Chicken', 'Wild Boar'],
    blendRatioSummary: '50% Hickory / 30% Apple / 20% Cherry',
    blendComponents: [
      { id: 'c1', woodType: 'Hickory', percentage: 50 },
      { id: 'c2', woodType: 'Apple', percentage: 30 },
      { id: 'c3', woodType: 'Cherry', percentage: 20 },
    ],
    ashOutput: 'Standard (1.0%)',
    idealSmokingTempRange: '225°F - 275°F',
    tags: ['Pulled Pork', 'Whole Hog', 'Carolina BBQ', 'Hickory Base', 'Ribs'],
    description: 'Designed specifically for low-and-slow pork shoulder butts and St. Louis ribs. Hickory punches through fat while fruitwoods sweeten the bark.',
    burnRateEfficiencyRating: 91.2,
    estimatedRunTimeHoursPer10Lbs: 8.8,
  },
  {
    id: 'blend-competition-ribs-poultry',
    name: 'Championship Red Bark Ribs & Poultry Blend',
    brand: 'Pitmaster Master Blend',
    category: 'Pitmaster Blends',
    btuPerLb: 8380,
    moisturePercent: 6.7,
    smokeDensity: 'Medium',
    barkImpact: 'Vibrant Deep Cherry Red',
    flavorNotes: '40% Cherry for dark red color, 40% Pecan for sweet nuttiness, and 20% Sugar Maple for subtle syrup glaze.',
    recommendedProteins: ['Pork', 'Chicken', 'Turkey', 'Duck'],
    blendRatioSummary: '40% Cherry / 40% Pecan / 20% Sugar Maple',
    blendComponents: [
      { id: 'c1', woodType: 'Cherry', percentage: 40 },
      { id: 'c2', woodType: 'Pecan', percentage: 40 },
      { id: 'c3', woodType: 'Maple', percentage: 20 },
    ],
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 275°F',
    tags: ['Competition Ribs', 'Cherry Red Bark', 'Poultry', 'Sweet Glaze'],
    description: 'Favored on the KCBS competition circuit for producing flawless mahogany-red rib surfaces that turn judges’ heads.',
    burnRateEfficiencyRating: 89.5,
    estimatedRunTimeHoursPer10Lbs: 8.5,
  },
  {
    id: 'blend-pnw-salmon-seafood',
    name: 'Pacific Northwest Seafood & Salmon Smoke',
    brand: 'Pitmaster Master Blend',
    category: 'Pitmaster Blends',
    btuPerLb: 8030,
    moisturePercent: 7.4,
    smokeDensity: 'Light',
    barkImpact: 'Subtle Golden Bronze',
    flavorNotes: '70% Alder wood base with 30% Apple wood. Delivers gentle, clean smoke that never overpowers delicate fish oils.',
    recommendedProteins: ['Seafood', 'Chicken', 'Pheasant'],
    blendRatioSummary: '70% Alder / 30% Apple',
    blendComponents: [
      { id: 'c1', woodType: 'Alder', percentage: 70 },
      { id: 'c2', woodType: 'Apple', percentage: 30 },
    ],
    ashOutput: 'Ultra Low (<0.5%)',
    idealSmokingTempRange: '180°F - 225°F',
    tags: ['Salmon', 'Smoked Fish', 'Pacific Northwest', 'Light Smoke', 'Cold Smoke'],
    description: 'The golden ratio for cold-smoking salmon, trout, sea bass, and soft cheeses without bitter creosote residue.',
    burnRateEfficiencyRating: 86.8,
    estimatedRunTimeHoursPer10Lbs: 7.9,
  },
  {
    id: 'blend-high-sear-mesquite-oak',
    name: 'Texas High-Heat Sear & Game Blend',
    brand: 'Pitmaster Master Blend',
    category: 'Pitmaster Blends',
    btuPerLb: 8900,
    moisturePercent: 5.7,
    smokeDensity: 'Bold',
    barkImpact: 'Dark Black & Searing Bark',
    flavorNotes: '50% Mesquite for intense thermal heat and earthy sharpness, paired with 50% Post Oak for steady temperature stability.',
    recommendedProteins: ['Beef', 'Bison', 'Venison', 'Wild Boar', 'Elk'],
    blendRatioSummary: '50% Mesquite / 50% Post Oak',
    blendComponents: [
      { id: 'c1', woodType: 'Mesquite', percentage: 50 },
      { id: 'c2', woodType: 'Post Oak', percentage: 50 },
    ],
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '275°F - 350°F',
    tags: ['High Heat', 'Sear', 'Mesquite', 'Steak', 'Game Meat'],
    description: 'Combines the intense thermal energy of West Texas Mesquite with the reliable thermal mass of Post Oak for high-heat roasting.',
    burnRateEfficiencyRating: 93.5,
    estimatedRunTimeHoursPer10Lbs: 9.3,
  },

  // --- SMOKER WOOD CHIPS (FOR LP / PROPANE / GAS & CHIP BOXES) ---
  {
    id: 'chip-hickory-premium',
    name: 'Hickory Smoker Wood Chips (LP Chip Tray)',
    brand: 'Western Premium BBQ',
    category: 'Smoker Wood Chips',
    btuPerLb: 8750,
    moisturePercent: 8.0,
    smokeDensity: 'Bold',
    barkImpact: 'Dark Espresso Bark',
    flavorNotes: 'Savory bacon aroma. Ideal for LP gas smoker chip boxes, foil packets, or electric smokers.',
    recommendedProteins: ['Pork', 'Beef', 'Chicken', 'Turkey'],
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '200°F - 300°F',
    tags: ['Wood Chips', 'LP Gas', 'Propane', 'Hickory', 'Chip Box'],
    description: '100% natural kiln-dried hickory wood chips designed for rapid smoke generation in propane & electric smoker chip trays.',
    burnRateEfficiencyRating: 90.0,
    estimatedRunTimeHoursPer10Lbs: 8.5,
  },
  {
    id: 'chip-applewood-sweet',
    name: 'Applewood Smoker Wood Chips (LP Chip Tray)',
    brand: 'Weber Firespice',
    category: 'Smoker Wood Chips',
    btuPerLb: 8150,
    moisturePercent: 8.2,
    smokeDensity: 'Light',
    barkImpact: 'Golden Amber Skin',
    flavorNotes: 'Mild, sweet, fruity smoke notes. Perfect for poultry, pork ribs, and salmon in LP propane smokers.',
    recommendedProteins: ['Pork', 'Chicken', 'Turkey', 'Seafood'],
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '200°F - 275°F',
    tags: ['Wood Chips', 'Apple', 'Sweet Smoke', 'LP Gas', 'Poultry'],
    description: 'A delicate fruitwood chip blend that ignites cleanly in LP gas tray burners without harsh bitterness.',
    burnRateEfficiencyRating: 88.0,
    estimatedRunTimeHoursPer10Lbs: 8.1,
  },
  {
    id: 'chip-mesquite-intense',
    name: 'Mesquite Smoker Wood Chips (LP Sear & Smoke)',
    brand: 'Oklahoma Joe\'s',
    category: 'Smoker Wood Chips',
    btuPerLb: 9100,
    moisturePercent: 6.8,
    smokeDensity: 'Heavy',
    barkImpact: 'Deep Dark Black Sear',
    flavorNotes: 'Pungent, earthen Texas mesquite. High heat release for rapid smoke penetration on LP burners.',
    recommendedProteins: ['Beef', 'Bison', 'Venison', 'Wild Game'],
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '250°F - 350°F',
    tags: ['Wood Chips', 'Mesquite', 'High BTU', 'LP Gas', 'Texas'],
    description: 'Intense Texas desert mesquite chips. Generates dense, aromatic smoke fast in gas burner chip boxes.',
    burnRateEfficiencyRating: 92.5,
    estimatedRunTimeHoursPer10Lbs: 9.0,
  },
  {
    id: 'chip-cherry-mahogany',
    name: 'Cherrywood Smoker Wood Chips (LP Color & Glaze)',
    brand: 'Western Premium BBQ',
    category: 'Smoker Wood Chips',
    btuPerLb: 8300,
    moisturePercent: 7.8,
    smokeDensity: 'Light',
    barkImpact: 'Vibrant Deep Red Mahogany',
    flavorNotes: 'Rich red color and sweet subtle fruitiness. Elevates pork chops, turkey legs, and ribs on gas smokers.',
    recommendedProteins: ['Pork', 'Chicken', 'Duck', 'Turkey'],
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 275°F',
    tags: ['Wood Chips', 'Cherry', 'Red Bark', 'LP Gas', 'Ribs'],
    description: 'Kiln-dried cherry wood chips that give gas-smoked meats an impressive deep mahogany red hue.',
    burnRateEfficiencyRating: 89.0,
    estimatedRunTimeHoursPer10Lbs: 8.3,
  },
  {
    id: 'chip-pecan-nutty',
    name: 'Pecan Smoker Wood Chips (LP Smooth Smoke)',
    brand: 'Masterbuilt Select',
    category: 'Smoker Wood Chips',
    btuPerLb: 8650,
    moisturePercent: 7.5,
    smokeDensity: 'Medium',
    barkImpact: 'Golden Mahogany',
    flavorNotes: 'Nutty, smooth, sweet aroma without bitterness. Versatile for long LP smoker cooks.',
    recommendedProteins: ['Pork', 'Beef', 'Chicken', 'Turkey'],
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 275°F',
    tags: ['Wood Chips', 'Pecan', 'Nutty', 'LP Gas', 'Versatile'],
    description: 'Smooth-burning pecan wood chips. Similar to hickory with a sweeter, nuttier finish.',
    burnRateEfficiencyRating: 91.0,
    estimatedRunTimeHoursPer10Lbs: 8.7,
  },
  {
    id: 'chip-jack-daniels-barrel',
    name: 'Jack Daniel\'s Whiskey Barrel Wood Chips',
    brand: 'Jack Daniel\'s BBQ',
    category: 'Smoker Wood Chips',
    btuPerLb: 8850,
    moisturePercent: 8.5,
    smokeDensity: 'Medium',
    barkImpact: 'Rich Whiskey Glaze Bark',
    flavorNotes: 'Crafted from authentic white oak aging barrels soaked in Tennessee Whiskey. Oak and caramel notes.',
    recommendedProteins: ['Beef', 'Pork', 'Chicken', 'Ribs'],
    ashOutput: 'Low (0.5-0.8%)',
    idealSmokingTempRange: '225°F - 300°F',
    tags: ['Wood Chips', 'Whiskey Barrel', 'Oak', 'Jack Daniels', 'LP Gas'],
    description: 'Made from genuine Jack Daniel\'s whiskey barrels. Imparts a sweet oak and caramel aroma in gas chip boxes.',
    burnRateEfficiencyRating: 91.5,
    estimatedRunTimeHoursPer10Lbs: 8.8,
  },
];

export function filterFuelDatabase(
  items: FuelDatabaseItem[],
  query: string,
  categoryFilter: string,
  smokeDensityFilter: string,
  proteinFilter: string,
  sortBy: 'btu' | 'name' | 'efficiency' | 'moisture'
): FuelDatabaseItem[] {
  const q = query.toLowerCase().trim();

  let filtered = items.filter((item) => {
    // Search query match
    if (q) {
      const matchName = item.name.toLowerCase().includes(q);
      const matchBrand = item.brand.toLowerCase().includes(q);
      const matchCategory = item.category.toLowerCase().includes(q);
      const matchFlavor = item.flavorNotes.toLowerCase().includes(q);
      const matchTags = item.tags.some((t) => t.toLowerCase().includes(q));
      const matchProteins = item.recommendedProteins.some((p) => p.toLowerCase().includes(q));
      const matchRatio = item.blendRatioSummary ? item.blendRatioSummary.toLowerCase().includes(q) : false;

      if (!matchName && !matchBrand && !matchCategory && !matchFlavor && !matchTags && !matchProteins && !matchRatio) {
        return false;
      }
    }

    // Category filter
    if (categoryFilter !== 'all' && item.category !== categoryFilter) {
      return false;
    }

    // Smoke density filter
    if (smokeDensityFilter !== 'all' && item.smokeDensity !== smokeDensityFilter) {
      return false;
    }

    // Recommended protein filter
    if (proteinFilter !== 'all') {
      const pMatch = item.recommendedProteins.some(
        (p) => p.toLowerCase() === proteinFilter.toLowerCase()
      );
      if (!pMatch) return false;
    }

    return true;
  });

  // Sorting
  filtered.sort((a, b) => {
    if (sortBy === 'btu') {
      return b.btuPerLb - a.btuPerLb;
    }
    if (sortBy === 'efficiency') {
      return b.burnRateEfficiencyRating - a.burnRateEfficiencyRating;
    }
    if (sortBy === 'moisture') {
      return a.moisturePercent - b.moisturePercent;
    }
    if (sortBy === 'name') {
      return a.name.localeCompare(b.name);
    }
    return 0;
  });

  return filtered;
}
